version: 1
formatters:
  simple:
    format: "[%(levelname)s] - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    #    rich_tracebacks: True
    formatter: simple
  #    stream: ext://sys.stdout
  rich:
    class: rich.logging.RichHandler
    rich_tracebacks: True
    formatter: simple
#    stream: ext://sys.stdout
root:
  handlers: [rich] # use console for normal logging

disable_existing_loggers: false
