default_language_version:
  python: python

exclude: "^docs/conf.py"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
      - id: detect-private-key

  # If you want to avoid flake8 errors due to unused vars or imports:
  - repo: https://github.com/myint/autoflake.git
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [--in-place, --remove-all-unused-imports, --remove-unused-variables]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)

  ## If like to embrace black styles even in the docs:
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.11.0
  #   hooks:
  #   - id: blacken-docs
  #     additional_dependencies: [black]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args:
          - "--max-line-length=120"
          - "--select=B,C,E,F,W,T4,B9"
          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,W504,F403,F401,E402"
  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  #  - repo: https://github.com/asottile/pyupgrade
  #    rev: v3.1.0
  #    hooks:
  #      - id: pyupgrade
  #        args: [ --py37-plus ]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types: [yaml]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=110
          - --include='\.pyi?$'
          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
#repos:
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.3.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: debug-statements
##    -   id: double-quote-string-fixer
#    -   id: name-tests-test
#    -   id: requirements-txt-fixer
#-   repo: https://github.com/asottile/setup-cfg-fmt
#    rev: v2.1.0
#    hooks:
#    -   id: setup-cfg-fmt
#-   repo: https://github.com/asottile/reorder_python_imports
#    rev: v3.8.5
#    hooks:
#    -   id: reorder-python-imports
#        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
#        args: [--py37-plus, --add-import, 'from __future__ import annotations']
