common: /hkfs/work/workspace/scratch/qv2382-madonna-ddp/madonna/configs/imagenet/vit/common.yaml

name: ab-2k
baseline: False
tracking:
  log_to_stdout: True
  tags:
    - scaling
training:
  iterations_per_train: 600
  checkpoint: null
  checkpoint_out_root: null
  save_period: 25
  ab:
    warmup_steps: 18600  # 9300/0.5
    steps_btw_syncing: 3000  # 1500 /0.5
    ddp_steps_after_sync: 600  # 300 /0.5
    lr_rebound_steps: 1500  # 750 /0.5
