start_epoch: 0
epochs: 400

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0
trainer: "MyOpt"
init_ddp: False

# ckpt path
resume_from_checkpoint: null

criterion:
  _target_: torch.nn.CrossEntropyLoss

#lr: 0.1
#lr_schedule:
#  _target_: torch.optim.lr_scheduler.StepLR
#  _partial_: True
#  step_size: 30
#  gamma: 0.1
#lr_warmup:
#  _target_: pytorch_warmup.LinearWarmup
#  _partial_: True
#  warmup_period: 100

lr_warmup_step_frequency: "epoch"
lr_warmup_step_args: null

init_opt_with_model: True
optimizer:
  _target_: madonna.optimizers.myopt.MyOpt
  _partial_: True
  reset_params: True
  contract_group_size: 3
  contract_method: "ddp"
#  momentum: 0.9
#  weight_decay: 1.0e-4
#  nesterov: True

lr: null
lr_schedule: null
lr_warmup: null
print_freq: 5
