start_epoch: 0
epochs: 90

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0
trainer: "qr_fix_train"
init_ddp: True

# ckpt path
resume_from_checkpoint: null

criterion:
  _target_: torch.nn.CrossEntropyLoss

lr: 0.01
lr_schedule:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: True
  step_size: 30
  gamma: 0.1
lr_warmup:
  _target_: pytorch_warmup.LinearWarmup
  _partial_: True
  warmup_period: 100

lr_warmup_step_frequency: "epoch"
lr_warmup_step_args: null

optimizer:
  _target_: torch.optim.SGD
  _partial_: True
  momentum: 0.9
  weight_decay: 1.0e-5
  nesterov: True

init_opt_with_model: False
print_freq: 10

qr_fixing:
  stability_frequency: 100
  delay: 1000
