# @package _global_

defaults:
  - _self_
  - data: cifar10.yaml # imagenet.yaml  # mnist.yaml
  - model: vit.yaml # general_torchvision.yaml # cirsean4.yaml #
  - tracking: mlflow.yaml # set tracking here or use command line (e.g. `python train.py tracking=tensorboard`)
  - training: qr_fix_trainer.yaml
  - log_dir: default.yaml
  # experiment configs allow for version control of specific configurations
  # e.g. hyperparameters for each combination of model and data
  - experiment: null
  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null
  # config for hyperparameter optimization
  - hparams_search: null
  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}
# pretty print config at the start of the run using Rich library
print_config: True
# set False to skip model training
train: True
validate: True
test: False
seed: 42
# default name for the experiment in mlflow, determines the default logging folder path
# (you can overwrite this name in experiment configs)
name: "qr-triu"
baseline: False

comm_method: "nccl"
cpu_training: False
enable_tracking: True
