# https://mlflow.org

# mlflow:
#   artifact_location: file:/hkfs/work/workspace/scratch/qv2382-madonna/mlflowsql/artifacts/
#   tracking_uri: sqlite:////hkfs/work/workspace/scratch/qv2382-madonna/mlflowsql/runsdb.sqlite
#   port: 24685

mlflow:
  artifact_location: file:/pfs/work7/workspace/scratch/qv2382-madonna/qv2382-madonna/mlflowsql/artifacts/
  tracking_uri: sqlite:////pfs/work7/workspace/scratch/qv2382-madonna/qv2382-madonna/mlflowsql/runsdb.sqlite
  port: 24685
#  experiment_name: ${name}
#  tags: null
#  save_dir: ${original_work_dir}/logs/mlruns
#  prefix: ""
