# https://wandb.ai

# wandb:
#   _target_: pytorch_lightning.loggers.wandb.WandbLogger
#   project: "template-tests"
#   # name: ${name}
#   save_dir: ${original_work_dir}/logs/wandb
#   offline: False # set True to store all logs only locally
#   id: null # pass correct id to resume experiment!
#   # entity: ""  # set to name of your wandb team
#   log_model: False
#   prefix: ""
#   job_type: "train"
#   group: ""
#   tags: []
logging_rank: all  # options: rank number of 'all', all logs from all
tracking_rank: 0
save_checkpoints: False
project: "lr-dist"
sweep: null
# tags:
#   - final
# sweep: sweep name
