# https://wandb.ai

logging_rank: 0  # options: rank number of 'all', all logs from all
tracking_rank: 0
save_checkpoints: False
project: "lr-dist"
sweep: null
log_file_root: /hkfs/work/workspace/scratch/qv2382-madonna-ddp/madonna/logs/experiments/runs/propulate/
log_to_stdout: True
tags:
  - propulate
# sweep: sweep name
