common: /hkfs/work/workspace/scratch/qv2382-madonna-ddp/madonna/configs/imagenet/resnet/common0.01.yaml
name: ab-16k-nogroups-weak
baseline: False
tracking:
  log_to_stdout: True
  tags:
    - scaling
    - no_groups
    - weak
data:
  local_batch_size: 64
training:
  iterations_per_train: 300
  use_early_stopping: true
  checkpoint: null
  checkpoint_out_root: null
  save_period: 25
  ab:
    warmup_steps: 9300
    steps_btw_syncing: 3000 # 1500
    ddp_steps_after_sync: 300
    lr_rebound_steps: 750


# training:
#   iterations_per_train: 75
#   checkpoint: null
#   checkpoint_out_root: null
#   save_period: 25
#   ab:
#     warmup_steps: 3750  # using epoch 50 instead of -> 9300/4
#     steps_btw_syncing: 600  # 1500 /4
#     ddp_steps_after_sync: 75  # 300 /4
#     lr_rebound_steps: 188  # 750 /4
