common: /hkfs/work/workspace/scratch/qv2382-madonna-ddp/madonna/configs/imagenet/resnet/common0.01.yaml
name: ab-2k
baseline: False
tracking:
  log_to_stdout: True
  tags:
    - scaling
training:
  iterations_per_train: 600
  checkpoint: null
  checkpoint_out_root: null
  save_period: 25
  ab:
    warmup_steps: 24000  # 9300/0.5
    steps_btw_syncing: 6000  # 1500 /0.5
    ddp_steps_after_sync: 300  # 300 /0.5
    lr_rebound_steps: 600  # 750 /0.5
