common: /hkfs/work/workspace/scratch/qv2382-madonna-ddp/madonna/configs/imagenet/resnet/common0.01.yaml
name: ab-8k-nogroups-weak
baseline: False
tracking:
  log_to_stdout: True
  tags:
    - scaling
    - no_groups
    - weak
data:
  local_batch_size: 128
training:
  iterations_per_train: 300
  use_early_stopping: true
  checkpoint: null
  checkpoint_out_root: null
  save_period: 25
  ab:
    warmup_steps: 9300
    steps_btw_syncing: 3000 # 1500
    ddp_steps_after_sync: 300
    lr_rebound_steps: 750

# training:
#   iterations_per_train: 150
#   checkpoint: null
#   checkpoint_out_root: null
#   save_period: 25
#   ab:
#     warmup_steps: 6150  # 9300/2
#     steps_btw_syncing: 1500  # 1500 /2
#     ddp_steps_after_sync: 150  # 300 /2
#     lr_rebound_steps: 325  # 750 /2
